/**
 * Auto-generated test: Test6
 *
 * Generated by MCP server
 */

import { SAPFioriAutomation } from './helper.js';
import dotenv from 'dotenv';

dotenv.config();

async function test6() {
  console.log('🚀 Running generated test "Test6"');
  const sap = new SAPFioriAutomation({ baseUrl: 'https://erp.jnj.com/', client: '100', language: 'EN' });
  try {
    await sap.initialize();
    await sap.login(process.env.SAP_USERNAME!);

    console.log('✅ Successfully logged into SAP Fiori Launchpad');
    await sap.act('Open the UMS Fiori');

    console.log('✅ Test Test6 completed');
    await new Promise(resolve => setTimeout(resolve, 5000));
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  } finally {
    await sap.cleanup();
  }
}

export default test6;

// auto-invoke when executed
(async () => {
  try {
    await test6();
  } catch (err) {
    console.error('Error in auto-invoked test:', err);
    process.exit(1);
  }
})();
