/**
 * Auto-generated test: Test6
 *
 * Generated by MCP server
 */

import { SAPFioriAutomation } from './helper.js';
import dotenv from 'dotenv';

dotenv.config();

async function test6() {
  console.log('🚀 Running generated test "Test6"');
  const sap = new SAPFioriAutomation({ baseUrl: 'https://ec2-184-73-255-6.compute-1.amazonaws.com:44300/sap/bc/ui2/flp?_sap-hash=JTIzU2hlbGwtaG9tZQ#Shell-home', client: '100', language: 'EN' });
  try {
    await sap.initialize();
    await sap.login(process.env.SAP_USERNAME!, process.env.SAP_PASSWORD!);

    console.log('✅ Successfully logged into SAP Fiori Launchpad');
    await sap.act(`https://ec2-184-73-255-6.compute-1.amazonaws.com:44300/sap/bc/ui2/flp?_sap-hash=JTIzU2hlbGwtaG9tZQ#Shell-home`);

    console.log('✅ Test Test6 completed');
    await new Promise(resolve => setTimeout(resolve, 5000));
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  } finally {
    await sap.cleanup();
  }
}

export default test6;

// auto-invoke when executed
(async () => {
  try {
    await test6();
  } catch (err) {
    console.error('Error in auto-invoked test:', err);
    process.exit(1);
  }
})();
