import express from 'express';
import path from 'path';
import fs from 'fs';
import { spawn } from 'child_process';

// simple state flag to track running test
let busy = false;
// track active test identifiers (sanitized names) to avoid duplicates
const activeTests = new Set<string>();

// sanitize a name to be filesystem-friendly
function sanitizeName(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// build a TypeScript test file from the JSON payload
function generateScript(data: any) {
  const testName: string = data.test_name || 'generated-test';
  const safe = sanitizeName(testName);
  const funcName = safe.replace(/-/g, '_');
  const fileName = `${safe}.ts`;

  const header = `/**
 * Auto-generated test: ${testName}
 *
 * Generated by MCP server
 */\n\n`;

  const imports = `import { SAPFioriAutomation } from './helper.js';
import dotenv from 'dotenv';

dotenv.config();

`;

  const bodyStart = `async function ${funcName}() {
  console.log('🚀 Running generated test "${testName}"');
  const sap = new SAPFioriAutomation({ baseUrl: '${data.url}', client: '100', language: 'EN' });
  try {
    await sap.initialize();
    await sap.login(process.env.SAP_USERNAME!);
    await sap.waitForFullPageLoad();
    const pageTitle = await sap.getPageTitle();
    if (pageTitle !== 'ERP Launchpad') {
      throw new Error('Expected page title "ERP Launchpad" but got: ", pageTitle);
    }
    else {
      console.log('✅ Successfully logged into ERP Launchpad');
    }

    await sap.act('Open the UMS Fiori');
    await sap.waitForFullPageLoad();
    const fioriPageTitle = await sap.getPageTitle();
    if (fioriPageTitle !== 'ERP Launchpad') {
      throw new Error('Expected page title "ERP Launchpad" but got: ", fioriPageTitle);
    }
    else {
      console.log('✅ Successfully opened UMS Fiori');
    }
`;

  let stepsCode = '';
  if (Array.isArray(data.steps)) {
    data.steps.forEach((step: any, index: number) => {
      const action = step.action || 'act';
      // normalize instruction and data
      const instr = (step.instruction || '').replace(/`/g, '\\`');
      const expectedResult = (step.expectedResult || '').replace(/`/g, '\\`');

      stepsCode += `\n    // Step ${index + 1}: ${action} - ${instr}\n`;

      switch (action) {
        case 'searchAndNavigate':
          stepsCode += `    await sap.searchAndNavigate(\`${instr}\`);\n`;
          break;
        case 'navigateToTile':
          stepsCode += `    await sap.navigateToTile(\`${instr}\`);\n`;
          break;
        case 'act':
          stepsCode += `    await sap.act(\`${instr}\`);\n`;
          break;
        case 'extract':
          stepsCode += `    await sap.extract(\`${instr}\`);\n`;
          break;
        case 'keyboardType':
          const text = step.data ? String(step.data).replace(/`/g, '\\`') : instr;
          const opts = step.options ? JSON.stringify(step.options) : '{}';
          stepsCode += `    await sap.keyboardType(\`${text}\`, ${opts});\n`;
          break;
        default:
          stepsCode += `    // unsupported action: ${action} - raw instruction: \`${instr}\`\n`;
      }

      // Wait for full page load after every step before proceeding
      stepsCode += `    await sap.waitForFullPageLoad();\n`;

      // If expectedResult is provided, verify it after the step completes
      if (expectedResult) {
        stepsCode += `    await sap.verifyExpectedResult(\`${expectedResult}\`);\n`;
      }
    });
  }

  const footer = `
    console.log('✅ Test ${testName} completed');
    await new Promise(resolve => setTimeout(resolve, 5000));
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  } finally {
    await sap.cleanup();
  }
}

export default ${funcName};

// auto-invoke when executed
(async () => {
  try {
    await ${funcName}();
  } catch (err) {
    console.error('Error in auto-invoked test:', err);
    process.exit(1);
  }
})();
`;

  return { fileName, content: header + imports + bodyStart + stepsCode + footer };
}

const app = express();
const uploadDir = path.join(process.cwd(), 'downloads', 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });

// Middleware to parse JSON and plain text bodies
app.use(express.json());
app.use(express.text());

app.post('/upload-data', (req, res) => {
  console.log('POST /upload-data received');
  if (busy) {
    console.warn('Request rejected: server busy');
    return res.status(409).json({ ok: false, error: 'Server busy' });
  }

  if (req.body === undefined || req.body === null || req.body === '') {
    console.warn('Request body empty');
    return res.status(400).json({ ok: false, error: 'No data provided' });
  }

  if (typeof req.body !== 'object') {
    console.warn('Request body not JSON, type=', typeof req.body);
    return res.status(400).json({ ok: false, error: 'Expected JSON body with instructions' });
  }

  const payload = req.body;
  const safeName = sanitizeName(payload.test_name || 'generated-test');
  if (activeTests.has(safeName)) {
    console.warn('Duplicate test request:', safeName);
    return res.status(409).json({ ok: false, error: 'Test already running' });
  }
  console.log('Payload parsed:', JSON.stringify(payload).slice(0, 200));

  const { fileName, content } = generateScript(payload);
  const scriptPath = path.join(process.cwd(), 'examples', 'sap', fileName);

  console.log('Generated script content:\n', content);
  console.log(`Writing script to ${scriptPath}`);
  fs.writeFileSync(scriptPath, content);

  busy = true;
  console.log('Starting child process to run', scriptPath);

  // Run tsx directly through node to avoid npm argument splitting (spaces in path issue).
  const tsxCli = path.join(process.cwd(), 'node_modules', 'tsx', 'dist', 'cli.mjs');
  if (!fs.existsSync(tsxCli)) {
    console.error('tsx CLI not found at', tsxCli, '; falling back to npm run test');
  }

  const child = spawn(
    process.execPath,
    fs.existsSync(tsxCli)
      ? [tsxCli, 'run-test.ts', scriptPath]
      : ['npx', 'tsx', 'run-test.ts', scriptPath],
    { stdio: 'inherit' }
  );

  child.on('exit', (code, signal) => {
    console.log(`Child process exited with code=${code} signal=${signal}`);
    busy = false;
    activeTests.delete(safeName);
    try {
      fs.unlinkSync(scriptPath);
      console.log('Deleted script file', scriptPath);
    } catch (err) {
      console.error('Error deleting script file', err);
    }
  });

  child.on('error', (err) => {
    console.error('Failed to start child process:', err);
    busy = false;
  });

  res.status(202).json({ ok: true, file: fileName });
});

app.get('/', (req, res) => res.send('MCP data upload server')); 

app.get('/status', (req, res) => {
  const state = busy ? 'running' : 'idle';
  if (busy) {
    // server is busy executing a test
    return res.status(202).json({ status: state, timestamp: new Date().toISOString() });
  }
  res.json({ status: state, timestamp: new Date().toISOString() });
});

const port = process.env.PORT ? Number(process.env.PORT) : 3005;
app.listen(port, () => console.log(`MCP server listening on http://localhost:${port}`));
