import express from 'express';
import path from 'path';
import fs from 'fs';
import { spawn } from 'child_process';

// simple state flag to track running test
let busy = false;
// track active test identifiers (sanitized names) to avoid duplicates
const activeTests = new Set<string>();

// sanitize a name to be filesystem-friendly
function sanitizeName(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// build a TypeScript test file from the JSON payload
function generateScript(data: any) {
  const testName: string = data.test_name || 'generated-test';
  const safe = sanitizeName(testName);
  const funcName = safe.replace(/-/g, '_');
  const fileName = `${safe}.ts`;

  const header = `/**
 * Auto-generated test: ${testName}
 *
 * Generated by MCP server
 */\n\n`;

  const imports = `import { SAPFioriAutomation } from './helper.js';
import { TestWrapper } from '../../src/test-wrapper.js';
import { ReportGenerator } from '../../src/report-generator.js';
import { mkdirSync } from 'fs';
import { join } from 'path';
import dotenv from 'dotenv';

dotenv.config();

`;

  const bodyStart = `async function ${funcName}() {
  console.log('🚀 Running generated test "${testName}"');

  // Create the report directory up front so screenshots go in the same folder
  const reportTs = ReportGenerator.buildTimestamp();
  const reportDir = join('reports', reportTs);
  mkdirSync(reportDir, { recursive: true });
  let screenshotCounter = 0;

  const wrapper = new TestWrapper('${testName}');
  wrapper.startTest('${testName}');
  const sap = new SAPFioriAutomation({ baseUrl: '${data.url}', client: '100', language: 'EN' });
  let testStatus: 'passed' | 'failed' = 'passed';
  try {
    await wrapper.timeStep('Initialize', 'Initialize SAP Automation', async () => {
      await sap.initialize();
    });

    await wrapper.timeStep('Login', 'Login to SAP system', async () => {
      await sap.login(process.env.SAP_USERNAME!);
      await sap.waitForFullPageLoad();
    });

    await wrapper.timeStep('Verify Login', 'Verify ERP Launchpad loaded (3 attempts, 5s each)', async () => {
      for (let attempt = 1; attempt <= 3; attempt++) {
        const pageTitle = await sap.getPageTitle();
        if (pageTitle === 'ERP Launchpad') {
          console.log('✅ Successfully logged into ERP Launchpad');
          return;
        }
        console.warn(\`⚠️  Attempt \${attempt}/3: expected "ERP Launchpad" but got "\${pageTitle}"\`);
        if (attempt < 3) {
          await new Promise(r => setTimeout(r, 5000));
          await sap.waitForFullPageLoad();
        }
      }
      const finalTitle = await sap.getPageTitle();
      if (finalTitle !== 'ERP Launchpad') {
        throw new Error('Expected page title "ERP Launchpad" but got: ' + finalTitle);
      }
    });

    await wrapper.timeStep('Open UMS Fiori', 'Navigate to UMS Fiori', async () => {
      await sap.act('Open the UMS Fiori');
      await sap.waitForFullPageLoad();
    });

    await wrapper.timeStep('Verify UMS Fiori', 'Verify UMS Fiori page loaded (3 attempts, 5s each)', async () => {
      for (let attempt = 1; attempt <= 3; attempt++) {
        const fioriPageTitle = await sap.getPageTitle();
        if (fioriPageTitle === 'Home') {
          console.log('✅ Successfully opened UMS Fiori');
          return;
        }
        console.warn(\`⚠️  Attempt \${attempt}/3: expected "Home" but got "\${fioriPageTitle}"\`);
        if (attempt < 3) {
          await new Promise(r => setTimeout(r, 5000));
          await sap.waitForFullPageLoad();
        }
      }
      const finalTitle = await sap.getPageTitle();
      if (finalTitle !== 'Home') {
        throw new Error('Expected page title "Home" but got: ' + finalTitle);
      }
    });
`;

  let stepsCode = '';
  if (Array.isArray(data.steps)) {
    data.steps.forEach((step: any, index: number) => {
      const action = step.action || 'act';
      // normalize instruction and data
      const instr = (step.instruction || '').replace(/`/g, '\\`');
      const expectedResult = (step.expectedResult || '').replace(/`/g, '\\`');
      const stepLabel = `Step ${index + 1}: ${action}`;
      const stepDesc = instr || action;

      // Handle screenshot action separately (it needs special step attachment)
      if (action === 'screenshot') {
        stepsCode += `\n    await wrapper.timeStep('${stepLabel}', \`${stepDesc || 'Take screenshot'}\`, async () => {
      screenshotCounter++;
      const screenshotFile = \`screenshot_${safe}_step\${screenshotCounter}.jpg\`;
      const screenshotPath = join(reportDir, screenshotFile);
      await sap.takeScreenshot(screenshotPath);
      // Attach screenshot filename (relative) to this step in the report
      wrapper.attachScreenshot(screenshotFile);
    });\n`;
        return; // skip the generic wrapper below
      }

      // Build the action call
      let actionCall = '';
      switch (action) {
        case 'searchAndNavigate':
          actionCall = `await sap.searchAndNavigate(\`${instr}\`);`;
          break;
        case 'navigateToTile':
          actionCall = `await sap.navigateToTile(\`${instr}\`);`;
          break;
        case 'act':
          actionCall = `await sap.act(\`${instr}\`);`;
          break;
        case 'extract':
          actionCall = `await sap.extract(\`${instr}\`);`;
          break;
        case 'keyboard': {
          const times = step.data ? Number(step.data) : 1;
          actionCall = `await sap.keyboard(\`${instr}\`, { times: ${times} });`;
          break;
        }
        case 'keyboardType': {
          const times = step.data ? Number(step.data) : 1;
          actionCall = `await sap.keyboardType(\`${instr}\`, { times: ${times} });`;
          break;
        }
        default:
          actionCall = `// unsupported action: ${action} - raw instruction: \`${instr}\``;
      }

      // Wrap in timeStep for tracking + add waitForFullPageLoad + expectedResult verification
      stepsCode += `\n    await wrapper.timeStep('${stepLabel}', \`${stepDesc}\`, async () => {
      ${actionCall}
      await sap.waitForFullPageLoad();`;

      if (expectedResult) {
        stepsCode += `\n      await sap.verifyExpectedResult(\`${expectedResult}\`);`;
      }

      stepsCode += `\n    });\n`;
    });
  }

  const footer = `
    console.log('✅ Test ${testName} completed');
  } catch (error: any) {
    testStatus = 'failed';
    console.error('❌ Error:', error);
    wrapper.logStep('Error', error.message || String(error), 'failure', { error: error.stack });
  } finally {
    // Always end the test and generate a report, regardless of success or failure
    wrapper.endTest(testStatus);

    try {
      await sap.cleanup();
    } catch (cleanupErr: any) {
      console.warn('⚠️ Cleanup error:', cleanupErr?.message || cleanupErr);
    }

    const reportFile = '${safe}';
    const reportPath = wrapper.generateReport(reportFile, reportDir);
    console.log('📊 Report generated at:', reportPath);

    if (testStatus === 'failed') {
      process.exit(1);
    }
  }
}

export default ${funcName};

// auto-invoke when executed
(async () => {
  try {
    await ${funcName}();
  } catch (err) {
    console.error('Error in auto-invoked test:', err);
    process.exit(1);
  }
})();
`;

  return { fileName, content: header + imports + bodyStart + stepsCode + footer };
}

const app = express();
const uploadDir = path.join(process.cwd(), 'downloads', 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });

// Middleware to parse JSON and plain text bodies
app.use(express.json());
app.use(express.text());

app.post('/upload-data', (req, res) => {
  console.log('POST /upload-data received');
  if (busy) {
    console.warn('Request rejected: server busy');
    return res.status(409).json({ ok: false, error: 'Server busy' });
  }

  if (req.body === undefined || req.body === null || req.body === '') {
    console.warn('Request body empty');
    return res.status(400).json({ ok: false, error: 'No data provided' });
  }

  if (typeof req.body !== 'object') {
    console.warn('Request body not JSON, type=', typeof req.body);
    return res.status(400).json({ ok: false, error: 'Expected JSON body with instructions' });
  }

  const payload = req.body;
  const safeName = sanitizeName(payload.test_name || 'generated-test');
  if (activeTests.has(safeName)) {
    console.warn('Duplicate test request:', safeName);
    return res.status(409).json({ ok: false, error: 'Test already running' });
  }
  console.log('Payload parsed:', JSON.stringify(payload).slice(0, 200));

  const { fileName, content } = generateScript(payload);
  const scriptPath = path.join(process.cwd(), 'examples', 'sap', fileName);

  console.log('Generated script content:\n', content);
  console.log(`Writing script to ${scriptPath}`);
  fs.writeFileSync(scriptPath, content);

  busy = true;
  console.log('Starting child process to run', scriptPath);

  // Run tsx directly through node to avoid npm argument splitting (spaces in path issue).
  const tsxCli = path.join(process.cwd(), 'node_modules', 'tsx', 'dist', 'cli.mjs');
  if (!fs.existsSync(tsxCli)) {
    console.error('tsx CLI not found at', tsxCli, '; falling back to npm run test');
  }

  // Run the generated script directly (it self-invokes and handles its own reporting)
  const child = spawn(
    process.execPath,
    fs.existsSync(tsxCli)
      ? [tsxCli, scriptPath]
      : ['npx', 'tsx', scriptPath],
    { stdio: 'inherit' }
  );

  child.on('exit', (code, signal) => {
    console.log(`Child process exited with code=${code} signal=${signal}`);
    busy = false;
    activeTests.delete(safeName);
    try {
      fs.unlinkSync(scriptPath);
      console.log('Deleted script file', scriptPath);
    } catch (err) {
      console.error('Error deleting script file', err);
    }
  });

  child.on('error', (err) => {
    console.error('Failed to start child process:', err);
    busy = false;
  });

  res.status(202).json({ ok: true, file: fileName });
});

app.get('/', (req, res) => res.send('MCP data upload server')); 

app.get('/status', (req, res) => {
  const state = busy ? 'running' : 'idle';
  if (busy) {
    // server is busy executing a test
    return res.status(202).json({ status: state, timestamp: new Date().toISOString() });
  }
  res.json({ status: state, timestamp: new Date().toISOString() });
});

const port = process.env.PORT ? Number(process.env.PORT) : 3005;
app.listen(port, () => console.log(`MCP server listening on http://localhost:${port}`));
